# Generated by Django 5.2.3 on 2025-06-18 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время услуги')),
                ('service_type', models.CharField(choices=[('main', 'Общий клининг'), ('general', 'Генеральная уборка'), ('build', 'Послестроительная уборка'), ('chemical', 'Химчистка ковров и мебели'), ('other', 'Иная услуга')], max_length=9, verbose_name='Вид услуги')),
                ('other_service_description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой')], max_length=5)),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('completed', 'Услуга оказана'), ('canceled', 'Услуга отменена')], max_length=10, verbose_name='Статус заявки')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
