# Generated by Django 5.2.3 on 2025-06-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('completed', 'Услуга оказана'), ('canceled', 'Услуга отменена')], default='new', max_length=10, verbose_name='Статус заявки'),
        ),
    ]
