# Generated by Django 5.2.3 on 2025-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контактные данные')),
                ('service_type', models.CharField(choices=[('main', 'Общий клининг'), ('general', 'Генералньая уборка'), ('building', 'Послестроительная уборка'), ('chemical', 'химчистка ковров и мебели')], default='main', max_length=8, verbose_name='Вид услуги')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой')], default='card', max_length=5, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
