# Generated by Django 5.2.3 on 2025-06-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicationmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('completed', 'Услуга оказана'), ('canceled', 'Услуга отменена')], default='new', max_length=10, verbose_name='Статус оказания услуги'),
        ),
    ]
