# Generated by Django 5.2.3 on 2025-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
    ]
